export class facturasGuia {
    constructor(
        public  TIPO_DOCUMENTO: string,
        public    FACTURA: string,
        public    ESTA_DESPACHADO: string,
        public   MONEDA_FACTURA: string,
        public   COMENTARIO_CXC: string,
        public    FECHA_RECIBIDO: string,
        public   PEDIDO: string,
        public   TOTAL_VOLUMEN:  number,
        public   TOTAL_PESO: number,
        public   TOTAL_IMPUESTO1:number,
        public   FECHA:any,
        public   FECHA_ENTREGA: any,
        public   TOTAL_FACTURA:number,
        public  FECHA_PEDIDO: string,
        public  TOTAL_MERCADERIA:number,
        public  ORDEN_COMPRA: null,
        public  TOTAL_UNIDADES:number,
        public  TIPO_CAMBIO:number,
        public   EMBARCAR_A: string,
        public  DIRECCION_FACTURA: string,
        public  MULTIPLICADOR_EV:number,
        public  OBSERVACIONES: string,
        public RUBRO1:number,
        public RUBRO2: string,
        public  RUBRO3: string,
        public   RUBRO4: string,
        public  RUBRO5: string,
        public  NIVEL_PRECIO: string,
        public  COBRADOR:number,
        public  RUTA: string,
        public   CONDICION_PAGO:string,
        public  ZONA: string,
        public  VENDEDOR:number,
        public  CLIENTE_DIRECCION:number,
        public  CLIENTE_CORPORAC:number,
        public  CLIENTE_ORIGEN:number,
        public  CLIENTE:number,
        public   PAIS: string,
        public   TOTAL_PESO_NETO:number,
        public  FECHA_RIGE: string,
        public   BASE_IMPUESTO1:number,
        public   BASE_IMPUESTO2:number,
        public   NOMBRE_CLIENTE: string,
        public   LONGITUD:number,
        public   LATITUD:number,
        public   FRIO_SECO: string,
        public   ENTREGA_INI:number,
        public   SELECCIONADA:boolean
    ){}
}


 