export const environment = {
  companyCode:"01",
  production: true,
  maxCharCodigoProd: 6,
  adminClave: '123456',
  TestURL:'test',
  postCLienteEspejoURL:'ActualizaClientes/',
  provinciaID: '?IdP=',
  cantonID: '&IdC=',
  distritoID: '&IdD=',
  clientesURL: 'Clientes/',
  provinciasURL: 'Provincias/',
  cantonesURL: 'Cantones/',
  distritosURL: 'Distritos/',
  busquedaCliente: 'Clientes2/',
  ruteroURL:'Rutero/',
  rutasURL:'Rutas/',
  entregaParam:'&entrega=',
  rutaParam:'?ruta=',
  rutaZonaURL:'Ruta_Zona',
  rutaFacturasURL:'Facturas/',
  getRutasZonasURL:'Rutas',
  zonasURL:'Zonas',
  idParam:'?ID=',
  camionesURL:'Camiones',
  guiasURL:'Guias',
  guiasURLEstadoParam:'?estado=',
  guiasRangoFecha:'guias-estado-rango-fecha?estado=',
  fechaInicio:'&fechaInicio=',
  fechaFin:'&fechaFin=',
  actualizaFacturasURL:'ActFac',
  actualizaFacLinUrl:'ActualizaFacLin/',
  clientesGuias:'ClientesGuia/',
  prdMode: true,
  facturasUrl:'Facturas/?id=',
  facturasGuiasUrl:'FactGuias?id=',
  manifiestoURL:'Manifiesto/?ID=',
  consultarGuia:'consultar-guia/?id=',
  facturasGuias:'get-facturas-guia/?Id=',
  clientesClierre:'ClientesCierre/?fecha='
};
