export const environment = {
  companyCode:"01",
  production: true,
  maxCharCodigoProd: 6,
  adminClave: '123456',
  TestURL: 'test',
  postCLienteEspejoURL:'ActualizaClientes/',
  provinciaID: '?IdP=',
  cantonID: '&IdC=',
  distritoID: '&IdD=',
  clientesURL: 'Clientes/',
  provinciasURL: 'Provincias/',
  cantonesURL: 'Cantones/',
  distritosURL: 'Distritos/',
  busquedaCliente: 'Clientes2/',
  ruteroURL:'Rutero/',
  rutasURL:'Rutas/',
  entregaParam:'&entrega=',
  rutaParam:'?ruta=',
  rutaZonaURL:'Ruta_Zona',
  rutaFacturasURL:'Facturas/',
  getRutasZonasURL:'Rutas',
  zonasURL:'Zonas',
  idParam:'?ID=',
  camionesURL:'Camiones',
  guiasURL:'Guias',
  guiasURLEstadoParam:'?estado=',
  actualizaFacturasURL:'ActFac',
  actualizaFacLinUrl:'ActualizaFacLin/',
  clientesGuias:'ClientesGuia/',
  prdMode: true,
  facturasUrl:'Facturas/?id=',
  manifiestoURL:'Manifiesto/?ID=',
  clientesClierre:'ClientesCierre/?fecha='
};
