export const environment = {
  production: true,
  maxCharCodigoProd: 6,
  adminClave: '123456',
  preURL: 'http://api_irp',
  TestURL: '_test',
  postURL: '.soportecr.xyz/api/',
  postCLienteEspejoURL:'ActualizaClientes/',
  mapboxKey:'pk.eyJ1IjoibWhlcnJhIiwiYSI6ImNrcWxhdXk4eTByMDUyd28xNnZ2b2hoMjMifQ.IrIAxPGO4oFiRVR8U5sqkA',
  provinciaID: '?IdP=',
  cantonID: '&IdC=',
  distritoID: '&IdD=',
  clientesURL: 'Clientes/',
  busquedaCliente: 'Clientes2/',
  provinciasURL: 'Provincias/',
  cantonesURL: 'Cantones/',
  distritosURL: 'Distritos/',
  rutasURL:'Rutas/',
  ruteroURL:'Rutero/',
  idParam:'?ID=',
  actualizaFacLinUrl:'ActualizaFacLin/',
  guiasURLEstadoParam:'?estado=',
  guiasURL:'Guias',
  actualizaFacturasURL:'ActualizaFacturas',
  entregaParam:'&entrega=',
  rutaParam:'?ruta=',
  rutaZonaURL:'Ruta_Zona',
  rutaFacturasURL:'Facturas/',
  zonasURL:'Zonas',
  camionesURL:'Camiones',
  prdMode: false,
};
